accounts/urls.py
from django.urls import path
from .views import signup



app_name = 'accounts'


urlpatterns = [
    path('signup',signup),
]

courses/urls.py
from django.urls import path
from .views import CoursList, CoursDetail , BrandList
from .api import cours_list_api , CoursDetailAPI

app_name = 'Courses'

urlpatterns = [
    path('',CoursList.as_view(),name='cours_list'),
    path('<slug:slug>',CoursDetail.as_view(),name='cours_detail'),
    path('brand/',BrandList.as_view(),name='brand_list'),
    #path('<int:id>/review/add',add_review,name='add_review'),
    path('api/list',cours_list_api),
    path('api/list/<int:pk>',CoursDetailAPI.as_view()),
    
    
    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from settings.views import home

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls',namespace='Courses')),
    path('',home),
    path("__debug__/", include("debug_toolbar.urls")),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from utils.generate_code import generate_code

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    image = models.ImageField(upload_to='accounts')
    code = models.CharField(max_length=10,default=generate_code)

    def __str__(self):
        return str(self.user)
    


class Phones(models.Model):
    user = models.ForeignKey(User,related_name='user_phones',on_delete=models.CASCADE)
    type = models.CharField(max_length=10)
    phone = models.CharField(max_length=10)


    def __str__(self):
        return str(self.user)

courses/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator,MinValueValidator
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.db.models.aggregates import Avg , Sum,Count

# Create your models here.


class Courses(models.Model):
    name = models.CharField(max_length=30)
    subtitle = models.TextField(max_length=10)
    description = models.TextField(max_length=20)
    image = models.ImageField(upload_to='courses')
    price = models.FloatField()
    tags = TaggableManager()
    video = models.URLField(null=True,blank=True)
    slug = models.SlugField(null=True,blank=True)
    user = models.ForeignKey(User,related_name='user_cours',on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)    
        super(Courses, self).save(*args, **kwargs) 


class Review(models.Model):
    user = models.ForeignKey(User,related_name='user_review',on_delete=models.SET_NULL,null=True,blank=True)
    cours = models.ForeignKey(Courses,related_name='cours_review',on_delete=models.SET_NULL,null=True,blank=True)
    review = models.TextField(max_length=500)
    rate = models.IntegerField(validators=[MaxValueValidator(5),MinValueValidator(0)]) 
    create_date = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return f"{self.user}-{self.cours}"
    


class Brand(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='brand')
    slug = models.SlugField(null=True,blank=True)
    user = models.ForeignKey(User,related_name='user_brand',on_delete=models.SET_NULL,null=True,blank=True)
    cours = models.ForeignKey(Courses,related_name='cours_brand',on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)    
        super(Brand, self).save(*args, **kwargs)

settings/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=50)
    logo = models.ImageField(upload_to='company')
    call_us = models.CharField(max_length=25,null=True,blank=True)
    email_us = models.CharField(max_length=25,null=True,blank=True)
    subtitle = models.TextField(max_length=200,null=True,blank=True)
    email = models.TextField(max_length=200,null=True,blank=True)
    phones = models.TextField(max_length=200,null=True,blank=True)
    address = models.TextField(max_length=200,null=True,blank=True)
    fb_link = models.URLField(null=True,blank=True)
    youtube_link = models.URLField(null=True,blank=True)
    tiktok_link = models.URLField(null=True,blank=True)
    insta_link = models.URLField(null=True,blank=True)
    android_store = models.URLField(null=True,blank=True)
    iphone_store = models.URLField(null=True,blank=True)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password'] 



class ActivateUser(forms.Form):
    code = forms.CharField(max_length=8)

courses/forms.py
from django import forms 
from .models import Review



class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review','rate']

accounts/views.py
from django.shortcuts import render,redirect
from .models import Profile,Phones
from .forms import SignupForm,ActivateUser


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            form.save()

    else:
        form = SignupForm()

    return render(request,'registration/signup.html',{'form':form})            

# Create your views here.

courses/views.py
from django.shortcuts import render
from .models import Courses,Review,Brand
from django.views import generic
from .forms import ReviewForm



# Create your views here.

class CoursList(generic.ListView):
    model = Courses
    paginate_by = 8

    def get_queryset(self):
        brand =  Brand.objects.all()
        queryset = Courses.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brand"] = Brand.objects.all()
        print(context)
        return context



class CoursDetail(generic.DetailView):
    model = Courses


class BrandList(generic.ListView):
    model = Brand

#def add_review(request,slug):
    #cours = Courses.objects.get(id=id)
    #form = ReviewForm(request.POST)
    #if form.is_valid():
        #myform = form.save(commit=False)
        #myform.user = request.user
        #myform.cours = cours
        #myform.save()
        #return redirect(f'/courses/{cours.id}')

settings/views.py
from django.shortcuts import render
from courses.models import Courses , Brand , Review
# Create your views here.


def home(request):
    brands = Brand.objects.all()
    courses = Courses.objects.all()
    return render(request,'settings/home.html',{'brands':brands,
                                                'courses':courses})

courses/templates/courses/brand_list.html
{% extends "base.html" %}
{% block body %}


<main>
    <!--? slider Area Start-->
    <section class="slider-area ">
        <div class="slider-active">
            <!-- Single Slider -->
            <div class="single-slider slider-height d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-7 col-md-12">
                            <div class="hero__caption">
                                <h1 data-animation="fadeInLeft" data-delay="0.2s">Online learning<br> platform</h1>
                                <p data-animation="fadeInLeft" data-delay="0.4s">Build skills with courses,
                                    certificates, and degrees online from world-class universities and companies</p>
                                <a href="#" class="btn hero-btn" data-animation="fadeInLeft" data-delay="0.7s">Join for
                                    Free</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ? services-area -->
    <div class="services-area">
        <div class="container">
            <div class="row justify-content-sm-center">
                <div class="col-lg-4 col-md-6 col-sm-8">
                    <div class="single-services mb-30">
                        <div class="features-icon">
                            <img src="static/assets/img/icon/icon1.svg" alt="">
                        </div>
                        <div class="features-caption">
                            <h3>60+ UX courses</h3>
                            <p>The automated process all your website tasks.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-8">
                    <div class="single-services mb-30">
                        <div class="features-icon">
                            <img src="assets/img/icon/icon2.svg" alt="">
                        </div>
                        <div class="features-caption">
                            <h3>Expert instructors</h3>
                            <p>The automated process all your website tasks.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-8">
                    <div class="single-services mb-30">
                        <div class="features-icon">
                            <img src="assets/img/icon/icon3.svg" alt="">
                        </div>
                        <div class="features-caption">
                            <h3>Life time access</h3>
                            <p>The automated process all your website tasks.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Courses area start -->
    <div class="courses-area section-padding40 fix">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-tittle text-center mb-55">
                        <h2>Our featured courses</h2>
                    </div>
                </div>
            </div>
            <div class="courses-actives">
                {% for brand in brand_list %}
                <div class="properties pb-20">
                    <div class="properties__card">
                        <div class="properties__img overlay1">
                            <a href=""><img src="{{brand.image.url}}" alt=""></a>
                        </div>
                        <div class="properties__caption">
                            <p>{{brand}}</p>
                            <h3><a href="#">{{cours.subtitle}}</a></h3>
                            <p>{{cours.description}}

                            </p>
                            {% for brand in brand_list.cours_brand.all %} 
                                <div class="properties__footer d-flex justify-content-between align-items-center">
                                    <div class="restaurant-name">
                                        <div class="rating">
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star-half"></i>
                                        </div>
                                        <p><span>{{review.user}}</span></p>
                                    </div>
                                    
                                    <div class="price">
                                        <span>${{cours.price}}</span>
                                    </div>
                                </div>
                            {% endfor %}
                            <a href="#" class="border-btn border-btn2">Find out more</a>
                        </div>

                    </div>
                </div>
                {% endfor %}


            </div>
        </div>
    </div>
    <!-- Courses area End -->
    <!--? About Area-1 Start -->
    <section class="about-area1 fix pt-10">
        <div class="support-wrapper align-items-center">
            <div class="left-content1">
                <div class="about-icon">
                    <img src="assets/img/icon/about.svg" alt="">
                </div>
                <!-- section tittle -->
                <div class="section-tittle section-tittle2 mb-55">
                    <div class="front-text">
                        <h2 class="">Learn new skills online with top educators</h2>
                        <p>The automated process all your website tasks. Discover tools and
                            techniques to engage effectively with vulnerable children and young
                            people.</p>
                    </div>
                </div>
                <div class="single-features">
                    <div class="features-icon">
                        <img src="assets/img/icon/right-icon.svg" alt="">
                    </div>
                    <div class="features-caption">
                        <p>Techniques to engage effectively with vulnerable children and young people.</p>
                    </div>
                </div>
                <div class="single-features">
                    <div class="features-icon">
                        <img src="assets/img/icon/right-icon.svg" alt="">
                    </div>
                    <div class="features-caption">
                        <p>Join millions of people from around the world learning together.</p>
                    </div>
                </div>

                <div class="single-features">
                    <div class="features-icon">
                        <img src="assets/img/icon/right-icon.svg" alt="">
                    </div>
                    <div class="features-caption">
                        <p>Join millions of people from around the world learning together. Online learning is as easy
                            and natural.</p>
                    </div>
                </div>
            </div>
            <div class="right-content1">
                <!-- img -->
                <div class="right-img">
                    <img src="assets/img/gallery/about.png" alt="">
                    {% for cours in courses_list %}
                        <div class="video-icon">
                            <a class="popup-video btn-icon" href="{{cours.video}}"><i
                                    class="fas fa-play"></i></a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <!-- About Area End -->
    <!--? top subjects Area Start -->
    <div class="topic-area section-padding40">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-tittle text-center mb-55">
                        <h2>Explore top subjects</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for brand in brand_list %}
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="single-topic text-center mb-30">
                        <div class="topic-img">
                            <img src="{{brand.image.url}}" alt="">
                            <div class="topic-content-box">
                                <div class="topic-content">
                                    <h3 ><a href="#" style="color: yellow;" >{{brand}}</a></h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                
                
            </div>
            <div class="row justify-content-center">
                <div class="col-xl-12">
                    <div class="section-tittle text-center mt-20">
                        <a href="courses.html" class="border-btn">View More Subjects</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- top subjects End -->
    <!--? About Area-3 Start -->
    <section class="about-area3 fix">
        <div class="support-wrapper align-items-center">
            <div class="right-content3">
                <!-- img -->
                <div class="right-img">
                    <img src="static/assets/img/gallery/about3.png" alt="">
                </div>
            </div>
            <div class="left-content3">
                <!-- section tittle -->
                <div class="section-tittle section-tittle2 mb-20">
                    <div class="front-text">
                        <h2 class="">Learner outcomes on courses you will take</h2>
                    </div>
                </div>
                <div class="single-features">
                    <div class="features-icon">
                        <img src="assets/img/icon/right-icon.svg" alt="">
                    </div>
                    <div class="features-caption">
                        <p>Techniques to engage effectively with vulnerable children and young people.</p>
                    </div>
                </div>
                <div class="single-features">
                    <div class="features-icon">
                        <img src="assets/img/icon/right-icon.svg" alt="">
                    </div>
                    <div class="features-caption">
                        <p>Join millions of people from around the world
                            learning together.</p>
                    </div>
                </div>
                <div class="single-features">
                    <div class="features-icon">
                        <img src="assets/img/icon/right-icon.svg" alt="">
                    </div>
                    <div class="features-caption">
                        <p>Join millions of people from around the world learning together.
                            Online learning is as easy and natural.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Area End -->
    <!--? Team -->
    <section class="team-area section-padding40 fix">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-tittle text-center mb-55">
                        <h2>Community experts</h2>
                    </div>
                </div>
            </div>
            <div class="team-active">
            {% for brand in brand_list %}
                <div class="single-cat text-center">
                        <div class="cat-icon">
                            <img src="{{brand.image.url}}" alt="">
                        </div>
                        <div class="cat-cap">
                            <h5><a href="services.html">{{brand}}</a></h5>
                            <p>The automated process all your website tasks.</p>
                            <p>{{brand.user}}</p>
                        </div>
                    </div>
            {% endfor %}
                
                
            </div>
        </div>
    </section>
    <!-- Services End -->
    <!--? About Area-2 Start -->
    <section class="about-area2 fix pb-padding">
        <div class="support-wrapper align-items-center">
            <div class="right-content2">
                <!-- img -->
                <div class="right-img">
                    <img src="assets/img/gallery/about2.png" alt="">
                </div>
            </div>
            <div class="left-content2">
                <!-- section tittle -->
                <div class="section-tittle section-tittle2 mb-20">
                    <div class="front-text">
                        <h2 class="">Take the next step
                            toward your personal
                            and professional goals
                            with us.</h2>
                        <p>The automated process all your website tasks. Discover tools and techniques to engage
                            effectively with vulnerable children and young people.</p>
                        <a href="#" class="btn">Join now for Free</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Area End -->
</main>
{% endblock body %}